file(READ "${SOURCE_DIR}/docs/requirements.md" requirements)
file(READ "${SOURCE_DIR}/docs/design.md" design)
file(READ "${SOURCE_DIR}/docs/tasks.md" tasks)
file(READ "${SOURCE_DIR}/docs/testing.md" testing)
string(REGEX MATCHALL "REQ-[0-9][0-9][0-9]" requirement_ids "${requirements}")
list(REMOVE_DUPLICATES requirement_ids)
foreach(requirement IN LISTS requirement_ids)
  foreach(document_name IN ITEMS design tasks testing)
    if(NOT "${${document_name}}" MATCHES "${requirement}")
      message(FATAL_ERROR "${requirement} is missing from ${document_name}.md")
    endif()
  endforeach()
endforeach()
file(GLOB docs "${SOURCE_DIR}/docs/*.md")
foreach(document IN LISTS docs)
  file(READ "${document}" content)
  if(content MATCHES "TODO|TBD|FIXME")
    message(FATAL_ERROR "Unresolved placeholder in ${document}")
  endif()
  string(REGEX MATCHALL [=[[A-Za-z0-9_.-]+\.md]=] links "${content}")
  foreach(target IN LISTS links)
    string(FIND "${content}" "](${target})" link_position)
    if(link_position EQUAL -1)
      continue()
    endif()
    get_filename_component(base "${document}" DIRECTORY)
    if(NOT EXISTS "${base}/${target}")
      message(FATAL_ERROR "Broken documentation link: ${document} -> ${target}")
    endif()
  endforeach()
endforeach()
